version: 2.1

jobs:
    # Update the sources directory with packages needed for this project.
    celestial-pi0w-build:
        docker:
            - image: pseudodesign/pseudo-oe-docker:latest
        resource_class: xlarge
        working_directory: /app/oe
        steps:
            # Checkout code and submodules
            - checkout
            - run: 
                name: Fetch Submodules
                command: git submodule update --init --recursive
            - run:
                name: Checksumming Sources Directory
                command: |
                  cd sources
                  { export LC_ALL=C;
                    find -type f -exec wc -c {} \; | sort; echo;
                    find -type f -exec md5sum {} + | sort; echo;
                    find . -type d | sort; find . -type d | sort | md5sum;
                  } | md5sum | awk '{print $1}' > ../.sources_md5.txt
                  cd ..
            - restore_cache:
                keys: 
                  - build-downloads-{{ checksum ".sources_md5.txt" }}-{{ checksum "celestial-pi0w-build/conf/bblayers.conf" }}
                  - build-downloads-{{ checksum ".sources_md5.txt" }}
                  - build-downloads
            - run:
                name: Fetch Downloads
                command: |
                    export BITBAKEDIR=$(pwd)/sources/poky/bitbake
                    source sources/poky/oe-init-build-env celestial-pi0w-build
                    bitbake -v core-image-base --runall=fetch 
            - save_cache:
                key: build-downloads-{{ checksum ".sources_md5.txt" }}-{{ checksum "celestial-pi0w-build/conf/bblayers.conf" }}
                paths: 
                    - "downloads"
            - run:
                name: Performing Build
                command: |
                    export BITBAKEDIR=$(pwd)/sources/poky/bitbake
                    source sources/poky/oe-init-build-env celestial-pi0w-build
                    bitbake core-image-base
            - store_artifacts:
                path: celestial-pi0w-build/tmp/deploy
                
workflows:
    pseudo-oe:
        jobs:
            - celestial-pi0w-build:
                filters:
                    branches:
                        only:
                            - celestial-pi0w-build
