version: 2.1

jobs:
    docker_bringup:
        docker:
            - image: pseudodesign/pseudo-oe-docker:latest
        steps:
            # Checkout code and submodules
            - checkout
            - run: git submodule update --init --recursive
            - run:
                name: Fetch Downloads
                command: |
                    pwd
                    export BITBAKEDIR=$(pwd)/sources/poky/bitbake
                    source sources/poky/oe-init-build-env celestial-pi0w-build
                    bitbake -v core-image-base -c fetchall 

workflows:
    pseudo-oe:
        jobs:
            - docker_bringup
