version: 2.1

jobs:
    # Update the sources directory with packages needed for this project.
    fetch_sources:
        docker:
            - image: pseudodesign/pseudo-oe-docker:latest
        working_directory: /app/oe
        steps:
            # Checkout code and submodules
            - checkout
            - run: git submodule update --init --recursive
            - restore_cache:
                key: build-sources
            - run:
                name: Fetch Downloads
                command: |
                    export BITBAKEDIR=$(pwd)/sources/poky/bitbake
                    source sources/poky/oe-init-build-env celestial-pi0w-build
                    bitbake -v core-image-base --runall=fetch 
            - save_cache:
                key: build-sources
                paths: 
                    - "sources"


workflows:
    pseudo-oe:
        jobs:
            - fetch_sources
