version: 2.1

jobs:
    docker_bringup:
        docker:
            - image: pseudodesign/pseudo-oe-docker:latest
        resource_class: small
        steps:
            # Checkout code and submodules
            - checkout
            - run: git submodule update --init --recursive
            - run:
                name: Run Build Script from "meta"
                command: ./celestial-pi0w-build/meta/run.sh

workflows:
    pseudo-oe:
        jobs:
            - docker_bringup
